#for dev environment only

version: "3"

services:
  app:
    container_name: tremorapi_app
    build:
      context: .
    ports:
      - "127.0.0.01:5000:5000"

    volumes:
      - ./app:/app
    environment:
      - TREMOR_DB_URI=postgresql://postgres:supersecret@tremorapi_dev:5432/
      - FLASK_ENV="staging"
      - APP_SETTINGS="staging"
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
      - TREMOR_API_KEY=123
      - TREMOR_API_SECRET="super-secret-shhhh"
      - APP_SETTINGS=development
    command: >
      sh -c "python -m flask run -h 0.0.0.0"
    depends_on:
      - db
  db:
    container_name: tremorapi_db
    image: postgres:9.2-alpine

  